# Generated by Django 3.2 on 2021-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jmeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadej jméno postavy. např. Onderic', max_length=60, verbose_name='Jméno postavy')),
            ],
            options={
                'ordering': ['jmeno'],
            },
        ),
    ]
