# Generated by Django 3.2 on 2021-04-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasa', models.CharField(help_text='Zadej název rasy, kterou má tvá postava.', max_length=20, verbose_name='Název rasy')),
                ('jmeno', models.OneToOneField(help_text='Zadej jméno postavy.', on_delete=django.db.models.deletion.CASCADE, to='witcher.jmeno')),
            ],
            options={
                'ordering': ['rasa'],
            },
        ),
        migrations.CreateModel(
            name='Povolani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('povolani', models.CharField(help_text='Zadej název povolání, kterou tvá postava vykonává.', max_length=50, verbose_name='Název povolání')),
                ('popis', models.CharField(max_length=1000, verbose_name='Popis povoláni')),
                ('jmeno', models.OneToOneField(help_text='Zadej název postavy', on_delete=django.db.models.deletion.CASCADE, to='witcher.jmeno')),
                ('rasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witcher.rasa')),
            ],
            options={
                'ordering': ['jmeno', 'povolani'],
            },
        ),
    ]
