# Generated by Django 3.2 on 2021-04-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0002_povolani_rasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(help_text='Zadej název povolání, kterou tvá postava vykonává.', max_length=50, verbose_name='Název povolání')),
                ('description', models.CharField(max_length=1000, verbose_name='Popis povoláni')),
            ],
            options={
                'ordering': ['name', 'profession'],
            },
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['race']},
        ),
        migrations.RenameField(
            model_name='name',
            old_name='jmeno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='jmeno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='rasa',
            new_name='race',
        ),
        migrations.RenameModel(
            old_name='Jmeno',
            new_name='Name',
        ),
        migrations.RenameModel(
            old_name='Rasa',
            new_name='Race',
        ),
        migrations.DeleteModel(
            name='Povolani',
        ),
        migrations.AddField(
            model_name='profession',
            name='name',
            field=models.OneToOneField(help_text='Zadej název postavy', on_delete=django.db.models.deletion.CASCADE, to='witcher.name'),
        ),
        migrations.AddField(
            model_name='profession',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witcher.race'),
        ),
    ]
