# Generated by Django 3.2 on 2021-04-15 09:52

from django.db import migrations, models
import django.db.models.deletion
import witcher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('elf', 'Elf'), ('člověk', 'Člověk'), ('trpaslík', 'Trpaslík'), ('goblin', 'Goblin'), ('upír', 'Upír')], default='člověk', help_text='Zadej název rasy, kterou má tvá postava.', max_length=20, verbose_name='Název rasy')),
                ('difference', models.CharField(blank=True, max_length=60, null=True, verbose_name='Odlišnost')),
            ],
            options={
                'ordering': ['race'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(help_text='Zadej název povolání, kterou tvá postava vykonává.', max_length=50, verbose_name='Název povolání')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Popis postavy.')),
                ('name', models.CharField(max_length=60, verbose_name='Jméno postavy')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=witcher.models.poster_path, verbose_name='Poster')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witcher.race')),
            ],
            options={
                'ordering': ['name', 'profession'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulek')),
                ('file', models.FileField(null=True, upload_to=witcher.models.attachment_path, verbose_name='Soubor')),
                ('type', models.CharField(blank=True, choices=[('obrazek', 'Obrazek'), ('video', 'Video'), ('ostatni', 'Ostatni')], default='obrazek', help_text='Vyberte povolený druh souboru', max_length=10, verbose_name='Typ souboru')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witcher.profession')),
            ],
            options={
                'ordering': ['title', 'type'],
            },
        ),
    ]
