# Generated by Django 3.2 on 2021-04-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jmeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadej jméno postavy. např. Onderic', max_length=60, verbose_name='Jméno postavy')),
            ],
            options={
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(help_text='Zadej název rasy, kterou má tvá postava.', max_length=20, verbose_name='Název rasy')),
                ('jmeno', models.OneToOneField(help_text='Zadej jméno postavy.', on_delete=django.db.models.deletion.CASCADE, to='witcher.jmeno')),
            ],
            options={
                'ordering': ['race'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(help_text='Zadej název povolání, kterou tvá postava vykonává.', max_length=50, verbose_name='Název povolání')),
                ('description', models.CharField(max_length=1000, verbose_name='Popis povoláni')),
                ('jmeno', models.OneToOneField(help_text='Zadej název postavy', on_delete=django.db.models.deletion.CASCADE, to='witcher.jmeno')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witcher.race')),
            ],
            options={
                'ordering': ['jmeno', 'profession'],
            },
        ),
    ]
