# Generated by Django 3.2 on 2021-04-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jmeno',
            new_name='Name',
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['name', 'profession']},
        ),
        migrations.RenameField(
            model_name='name',
            old_name='jmeno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='jmeno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='jmeno',
            new_name='name',
        ),
    ]
