# Generated by Django 3.2 on 2021-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.CharField(default='člověk', help_text='Zadej název rasy, kterou má tvá postava.', max_length=20, verbose_name='Název rasy'),
        ),
    ]
