# Generated by Django 3.2 on 2021-04-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0002_alter_race_race'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='name',
            new_name='profession',
        ),
    ]
